-- =============================================================================
-- AlloyDB Schema for Multi-Agent Productivity Assistant
-- Run this script against your AlloyDB instance after setup.
-- Requires: google_ml_integration extension (for embedding() function)
--           vector extension (for pgvector / VECTOR type)
-- =============================================================================

-- Enable extensions
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS google_ml_integration;

-- Grant the embedding function to all database users
GRANT EXECUTE ON FUNCTION embedding TO PUBLIC;

-- =============================================================================
-- Tasks Table
-- =============================================================================
CREATE TABLE IF NOT EXISTS tasks (
    id            SERIAL PRIMARY KEY,
    title         TEXT    NOT NULL,
    description   TEXT    DEFAULT '',
    priority      TEXT    DEFAULT 'medium'
                          CHECK (priority IN ('low', 'medium', 'high')),
    status        TEXT    DEFAULT 'pending'
                          CHECK (status IN ('pending', 'in_progress', 'done')),
    due_date      TEXT    DEFAULT '',
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- Notes Table  (AlloyDB AI: vector embedding for semantic search)
-- =============================================================================
CREATE TABLE IF NOT EXISTS notes (
    id          SERIAL PRIMARY KEY,
    title       TEXT    NOT NULL,
    content     TEXT    NOT NULL,
    tags        TEXT    DEFAULT '',
    -- 768-dimension vector generated by text-embedding-005 via AlloyDB AI
    embedding   VECTOR(768),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ScaNN index for fast approximate nearest-neighbour search on notes
CREATE INDEX IF NOT EXISTS notes_embedding_scann_idx
    ON notes USING scann (embedding cosine);

-- =============================================================================
-- Calendar Events Table
-- =============================================================================
CREATE TABLE IF NOT EXISTS events (
    id               SERIAL PRIMARY KEY,
    title            TEXT    NOT NULL,
    date             TEXT    NOT NULL,
    time             TEXT    NOT NULL,
    duration_minutes INTEGER DEFAULT 60,
    description      TEXT    DEFAULT '',
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =============================================================================
-- Verify setup
-- =============================================================================
SELECT 'AlloyDB schema created successfully' AS status;
